// GENERATED by scripts/certify-seeds.mjs — do not edit by hand.
//
// Hole seeds that pass certify.js: a fork in the aim heatmap (M1) plus a real
// cost to the naive centre-line aim or a divergence between player profiles
// (M3 or M2), measured at the scratch profile. Caddie deals its two-shotters
// from these instead of from the raw seed stream, so a hole with one obvious
// answer never reaches a player.
//
// Par 3s are absent on purpose. They are not certifiable at this board
// resolution — a real pin sits about a fifth of a tile from the green's edge —
// so they still come from the raw stream. See docs/research/03.
//
// Stored big-endian uint32, base64. 237 par 4s, 220 par 5s.

function decode(b64) {
  const bin = atob(b64);
  const buf = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
  const dv = new DataView(buf.buffer);
  const out = new Uint32Array(bin.length / 4);
  for (let i = 0; i < out.length; i++) out[i] = dv.getUint32(i * 4, false);
  return out;
}

export const CERTIFIED_PAR4 = decode('AGkNNgDI/LoBCxmpARbHEQFrCS0Cy7KGBEtwlgSk6FUF7jbeB3miVgiwy7II/pYJCkfkkg1j8SUNamjqE1svfheuZW0XzDgCGCB6HhjsBo4aBV1VGnD6QRqOzNYbWllGHBo4Th9UF3YhjTzJInabziS7boklOTCiJkbaASc75m4nm9XyKQlu1SpMRZkrDCShK4Nu9SvXsREtLK0CLW7J8S3OuXUuRgPJLxgH/i8jtWYvj1JSMJFOSTCc+7EwryDeMdQlDTHmSjoy8/OZM1+QhTPLLXE0VJzyNWJGUTbtsck4hMqpOXnXFjo5th46RWOGO7L8aT6BPqU+81NWP0zLFUSP185FMeRBRbtTwkbI/SFKwrtRS45HwUv55K1OsMwZTrx5gU8caQVSVkgtUly/8lLUCkZTFic1UzP5ylS47X1WRFj1WQbtyVsndipdEtEmXWxI5V6MF3Fel8TZYjgLSmKjqDZmi0E5ZwkDUmigHDJo1ou5aUIopWmiGClprcWRacuYJmorh6pq9xQabaeDwW25qO5uEyCtcBxOPnBeay1wfD3CcbNnHnM4WtF0Y9bFdg0U0nbkTqp3OJDGd/2lcXhvuiJ5HXP9eTtGknmJEOl6BtMCehKAanq0jN2BHJ3FgY6ydoRc9LKHwZX5h81DYYfY8MmH6xX2iEsFeokEbL2Jgi7Wiq2qyo2+CfWPEwXmkCCvRZAy1HKRCg5KkWn9zpMBFq6TbLOak8D1tpRur5GYFCulmGhtwZldei6bokzpm7RyFp23J+KeWTRVntB+qZ+QXbGgW+ohoaU4qqfjyZWpmLUKrGb3Rq0yg7ax2fvBsqWIMbW8XyG284h9t9zngrgfBHG4fvP1uhYM1brtRq27CxlCvKIyIrzkTxG++SoKv8S2esBycFXA0l/ZwPvf1sNS177DoKIVxUngIsYhGfrG2oE9x46y3ckly73JT0u6yZ0WEcp6x67MU/19zF+q5czRv5bQrasx0Mt9xtGXCjbUZUxy1XL10dWcdc7WSi+p13WrndihJ5HbD3pJ3E0bat3SDx3eJlE53xtdpuIrvNHjFRvW5XfBJudFSY3nUPb1527Jiuh8cunpBeJq6573Qex2MRns8/My7ur7lu9Ec1XwIiTy8NuMNfJypRXy5LnG8vBnLvMm1rXzsEY28/JjJfP+EI30G+Mi9F4AEfVHXxb1iXwF9gDGWfYHPh73Pmd6+aEMyvpOxqX6WnQN+yYAff0dCOH9+rp+/tH0Vv8fvq3/MePa');

export const CERTIFIED_PAR5 = decode('AbJbvwKQDVwCus97AuRPeAM4kZQDW5nMBmbDVAZ+HiQI1RYMCsBxCAv3mmQPE6b3DyXMJBB0UFARP9zAEstIOBPknv8T9sQsFS3tiBsMju8ejwLLHpV6kB/R2Y8gr4ssIiOb1CQULHMk62ZLJZ+X6yW28rsm1sFHKKMHjCjZdxMo5SR7KQL3EC2HZuMt8wPPLgpeny9Bh/sw2KDbMVZi9DMYPfMzeC13NS0Y7DcpVvM3fZkPOBK1+DhbSqw7AAzrOymM6DyugJs/HNNTP+7XiD/6hPBAs+wzQQguT0KTmcdD9EMgROqRr0UUEaxFSoEzRqsqjEcLGhBHyvkYSPuqr0lnR5tLEIWoS15P/0xycSNNwPVPTodMHE81BfdQKhJkUO8nD1EM+aRRTxaTUZerR1Ju5R9TBAIIU1HMX1RxmutU6OU/WB2OxFnrFytZ9sSTWhSXKFrCUQNazf5rWzRltFtAExxbjd1zW6uwCFwi+lxfLiPkX/M4j2EqYetiqh/7Y+fBHGZbSXdp6Wq7aklaP2u9auduVT2cboutI28sd3Ryupi4dDpWyHaWhFN2qKmAdtNrn3dWY1t3aIiIeVPjhHnLLdh69qnMe83jpHylHXx+PDZcf2eyUH+eIdd/u/RsgHvTdIGshQuDQ53rhu+RxIcseRCJOtxEiulP9IvrS+uMVujXjR0/pI/Nr0uQUKcHkFxUb5HiikSS0R7slef13Jb1nzuX3v5AmLY4GJntYXSaWP5gmq1AfJrEm0yeO2HAnpTZf6AgRPehyYMEowCsYKVL9uClXNnrphELi6YcuPOnZgd8p7PR06oWdyOqcTEEqnZmp6q++1urPL10rcJq/K342oOvWYPcsM2UhLGkzlyzm9bAtKmAH7XsVuO2w5C7tzWlbLfXsd+3419Ht/WEdLnaZ6u7ZdMju4OluLubAIi/Ecb8wGBLKMCLDUfBdGxMwYvHHMO5PwfE/BXLxc4aAMfWBW/I3nkryd8zAMqBP3PM4+TDzUPUR9Td2OjaCEiv2z9yC9uxhrzb86Or3L8wG9zFp+DdSJ+c4SsC/OWQXhjl+/sE5j4X8+jKPUDpDFov6TXaLOpPMPPrLOKQ64zSFOxGOVfwn+cL8LIMOPER+7zx0drE9IJKa/SN99P1WYRD9XdW2PlTQnP6Hs7j/gzfqw==');

/** The pool a given par draws from, or null where certification does not apply. */
export function certifiedPool(par) {
  if (par === 4) return CERTIFIED_PAR4;
  if (par === 5) return CERTIFIED_PAR5;
  return null;
}
