// Build the certified-seed table.
//
// `certify.js` is too expensive to run in a browser — one `strokesField` is
// about a second — so the fork can never be a live reroll gate. It can be an
// OFFLINE one: sweep the seed space here, keep the seeds that certify, commit
// the list, and let Caddie deal only from it.
//
// Par 3s are deliberately absent. They are not certifiable, and the reason is
// structural rather than a shortcoming of the generator — see
// docs/research/03. They keep coming from the raw seed stream.
//
// Usage:
//   node scripts/certify-seeds.mjs --par 4 --target 800 --shard 0 --shards 4
//   node scripts/certify-seeds.mjs --merge

import { writeFileSync, readFileSync, existsSync, mkdirSync, appendFileSync } from 'node:fs';
import { caddieHoleShape, caddieHoleCourse } from '../src/engine/caddierec.js';
import { certifyHole } from '../src/engine/certify.js';
import { handicapById } from '../src/engine/dispersion.js';

const argv = process.argv.slice(2);
const arg = (k, d) => {
  const i = argv.indexOf('--' + k);
  return i >= 0 ? argv[i + 1] : d;
};
const OUT = 'scratch-certified';

// Certification runs at SCRATCH. A hole that forks for a scratch player is the
// common reference; M2 exists precisely because the same hole plays differently
// for other dispersions, and certifying separately per handicap would quadruple
// the sweep to buy four disjoint hole pools nobody asked for.
const PROFILE = handicapById('scratch');

function sweep({ par, target, shard, shards }) {
  mkdirSync(OUT, { recursive: true });
  const file = `${OUT}/par${par}-${shard}.txt`;
  writeFileSync(file, '');
  let found = 0;
  let tried = 0;
  const t0 = Date.now();
  // Each shard walks its own arithmetic progression, so shards never collide
  // and the union is reproducible from (target, shards) alone.
  for (let n = 0; found < target; n++) {
    const seed = (2166136261 + (n * shards + shard) * 2654435761) >>> 0;
    const shape = caddieHoleShape(seed);
    if (shape.par !== par) continue; // free: three RNG draws, no course built
    tried++;
    const course = caddieHoleCourse(seed);
    const cert = certifyHole(course, { skipDivergence: true, sweeps: 5, profile: PROFILE });
    if (!cert.pass) continue;
    appendFileSync(file, seed + '\n');
    found++;
    if (found % 25 === 0) {
      const rate = ((found / tried) * 100).toFixed(0);
      const per = ((Date.now() - t0) / 1000 / tried).toFixed(2);
      process.stdout.write(`par${par} shard${shard}: ${found}/${target} (${rate}% of ${tried} tried, ${per}s each)\n`);
    }
    if (tried > target * 40) break; // a pass rate this low means something broke
  }
  process.stdout.write(`par${par} shard${shard}: DONE ${found} certified from ${tried} tried\n`);
}

function merge() {
  const out = {};
  for (const par of [4, 5]) {
    const seeds = new Set();
    for (let s = 0; s < 16; s++) {
      const f = `${OUT}/par${par}-${s}.txt`;
      if (!existsSync(f)) continue;
      for (const line of readFileSync(f, 'utf8').split('\n')) {
        const t = line.trim();
        // Number('') is 0, not NaN. Every shard file ends in a newline, so the
        // obvious `Number(line.trim())` quietly filed a phantom seed 0 in both
        // tables — and seed 0 happens to derive a par 4, so it passed unnoticed
        // in the par-4 pool and only surfaced as a mis-filed par 5.
        if (!t) continue;
        const n = Number(t);
        if (Number.isInteger(n) && n > 0 && n <= 0xffffffff) seeds.add(n >>> 0);
      }
    }
    // sorted, so the table is a canonical function of the sweep and a rerun
    // that finds the same seeds produces a byte-identical file
    out[par] = [...seeds].sort((a, b) => a - b);
  }
  const enc = (arr) => {
    const buf = new Uint8Array(arr.length * 4);
    const dv = new DataView(buf.buffer);
    arr.forEach((v, i) => dv.setUint32(i * 4, v >>> 0, false));
    let bin = '';
    for (const b of buf) bin += String.fromCharCode(b);
    return btoa(bin);
  };
  const body = `// GENERATED by scripts/certify-seeds.mjs — do not edit by hand.
//
// Hole seeds that pass certify.js: a fork in the aim heatmap (M1) plus a real
// cost to the naive centre-line aim or a divergence between player profiles
// (M3 or M2), measured at the scratch profile. Caddie deals its two-shotters
// from these instead of from the raw seed stream, so a hole with one obvious
// answer never reaches a player.
//
// Par 3s are absent on purpose. They are not certifiable at this board
// resolution — a real pin sits about a fifth of a tile from the green's edge —
// so they still come from the raw stream. See docs/research/03.
//
// Stored big-endian uint32, base64. ${out[4].length} par 4s, ${out[5].length} par 5s.

function decode(b64) {
  const bin = atob(b64);
  const buf = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
  const dv = new DataView(buf.buffer);
  const out = new Uint32Array(bin.length / 4);
  for (let i = 0; i < out.length; i++) out[i] = dv.getUint32(i * 4, false);
  return out;
}

export const CERTIFIED_PAR4 = decode('${enc(out[4])}');

export const CERTIFIED_PAR5 = decode('${enc(out[5])}');

/** The pool a given par draws from, or null where certification does not apply. */
export function certifiedPool(par) {
  if (par === 4) return CERTIFIED_PAR4;
  if (par === 5) return CERTIFIED_PAR5;
  return null;
}
`;
  writeFileSync('src/engine/certified.js', body);
  console.log(`wrote src/engine/certified.js — ${out[4].length} par 4s, ${out[5].length} par 5s`);
}

if (argv.includes('--merge')) merge();
else sweep({ par: Number(arg('par', 4)), target: Number(arg('target', 100)), shard: Number(arg('shard', 0)), shards: Number(arg('shards', 1)) });
